name: PR Custom Review Status

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - review_request_removed
  pull_request_review:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pr-custom-review
        uses: joao-paulo-parity/pr-custom-review@tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: './.github/pr-custom-review-config.yml'
